package go_cake

const MAX_URL_LENGTH = 2048
const MAX_INPUT_PAYLOAD_SIZE = 2097152 // 2MB
const MAX_REQUEST_TIME_MS = 1000
const MAX_INPUT_ITEMS = 1000
const MAX_OUTPUT_ITEMS = 1000
const ALLOWED_ACCEPT_HEADER_0 = "*/*"
const ALLOWED_ACCEPT_HEADER_1 = "application/json"
const ALLOWED_REQUEST_CONTENT_TYPE = "application/json"
const RESPONSE_CONTENT_TYPE = "application/json; charset=utf-8"
const RESPONSE_CACHE_CONTROL = "no-store"
const OBJECT_ID_FIELD_ERROR_NAME = "ObjectID"
const HTTP_REQUEST_GET_METHOD = "GET"
const HTTP_REQUEST_POST_METHOD = "POST"
const HTTP_REQUEST_PUT_METHOD = "PUT"
const HTTP_REQUEST_PATCH_METHOD = "PATCH"
const HTTP_REQUEST_DELETE_METHOD = "DELETE"
const HTTP_REQUEST_OPTIONS_METHOD = "OPTIONS"
const FIELD_ANY = "*"
